# Bibliotecas Algebricas

In [1]:
from src.linear_algebra_resolution.gaussian_elimination import gaussian_elimination
import numpy as np
from numpy import loadtxt

# Testando o Sistema

## Pivotação Parcial

In [3]:
gauss_partial_pivoting_b_path = 'test_matrix/linear_resolution_simple_b.csv'
gauss_partial_pivoting_b = loadtxt(gauss_partial_pivoting_b_path, delimiter=',')

gauss_partial_pivoting = gauss_partial_pivoting_b[:,:-1]
b = gauss_partial_pivoting_b[:,-1]

In [4]:
gauss_partial_pivoting

array([[5., 1., 0., 2., 1.],
       [0., 4., 0., 1., 2.],
       [1., 1., 4., 1., 1.],
       [0., 1., 2., 6., 0.],
       [0., 0., 1., 2., 4.]])

In [5]:
b

array([1., 2., 3., 4., 5.])

In [6]:
resp, hist, forward_matrix = gaussian_elimination(gauss_partial_pivoting, b)
gauss_partial_pivoting @ resp

array([1., 2., 3., 4., 5.])

## Pivotação Total

In [7]:
gauss_total_pivoting_b_path = 'test_matrix/gauss_total_pivoting_b.csv'
gauss_total_pivoting_b = loadtxt(gauss_total_pivoting_b_path, delimiter=',')

gauss_total_pivoting = gauss_total_pivoting_b[:,:-1]
b = gauss_total_pivoting_b[:,-1]

FileNotFoundError: test_matrix/gauss_total_pivoting_b.csv not found.

In [20]:
resp, hist_, x_forward = gaussian_elimination(gauss_total_pivoting, b)
gauss_total_pivoting @ resp

array([-0.2,  0.8,  1.5,  1.2])

In [22]:
hist_.apply_operations_matrix()

array([[ 1. ,  1. ,  1. ,  1. ],
       [ 0. ,  1. ,  4. , 12. ],
       [ 0. ,  0. , -2. , -9. ],
       [ 0. ,  0. ,  0. , -0.5]])

## Exibindo mensagem de erro

In [10]:
X_zeros = np.zeros([10, 10])
b_zeros = np.zeros(10)

gaussian_elimination(X_zeros, b_zeros)

aq


NameError: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] not exists valid value values to pivot number 0