In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.qr_decomposition import qr_decomposition, qr_method

In [14]:
x = loadtxt('test_matrix/householder_simetric.csv', delimiter=',')

In [15]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [16]:
x.T

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [17]:
x.shape

(4, 4)

In [18]:
q, r, eignvalues = qr_method(x)

In [19]:
eignvalues

array([ 6.84462111,  2.26632939, -2.19531496,  1.08436446])

In [24]:
q @ r

array([[ 4.00000000e+00,  1.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00, -5.08295319e-16,
         1.00000000e+00],
       [-2.00000000e+00, -2.35286067e-16,  3.00000000e+00,
        -2.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -2.00000000e+00,
        -1.00000000e+00]])

In [25]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [21]:
q, r = qr_decomposition(x)