In [17]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.householder_method import householder
from src.linear_algebra_resolution.power_methods import inverse_power_method, regular_power_method
from src.linear_algebra_resolution.qr_decomposition import qr_decomposition, qr_method

In [2]:
x = loadtxt('test_matrix/householder.csv', delimiter=',')

In [3]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [4]:
a_hat, h = householder(x)

In [5]:
a_hat

array([[ 4.00000000e+00,  3.00000000e+00, -1.99840144e-16,
        -8.43769499e-16],
       [ 3.00000000e+00,  3.33333333e+00,  1.66666667e+00,
        -2.88657986e-16],
       [-1.99840144e-16,  1.66666667e+00, -1.32000000e+00,
        -9.06666667e-01],
       [-8.43769499e-16,  2.22044605e-16, -9.06666667e-01,
         1.98666667e+00]])

In [6]:
h

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.13333333,  0.93333333],
       [ 0.        , -0.66666667, -0.66666667,  0.33333333],
       [ 0.        ,  0.66666667, -0.73333333, -0.13333333]])

In [22]:
q, r = qr_method(x, h)

In [11]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [13]:
np.around(q, 5)

array([[ 6.84462, -0.     , -0.     ,  0.     ],
       [-0.     ,  2.26633,  0.09914, -0.     ],
       [-0.     ,  0.09914, -2.19531,  0.     ],
       [ 0.     ,  0.     , -0.     ,  1.08436]])

In [14]:
np.around(r, 5)

array([[ 0.71805,  0.20559, -0.17218, -0.64226],
       [ 0.3292 ,  0.33125,  0.84922,  0.24642],
       [ 0.34192, -0.91429,  0.2148 ,  0.03202],
       [ 0.50905,  0.1099 , -0.4506 ,  0.72509]])

In [19]:
regular_power_method(x)

(array([ 0.71830962,  0.22197083, -0.55692057,  0.35298686]),
 6.844569183337946,
 True)

In [20]:
q, r = qr_decomposition(x)

In [21]:
q @ r

array([[ 4.00000000e+00,  1.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00, -5.08295319e-16,
         1.00000000e+00],
       [-2.00000000e+00, -2.35286067e-16,  3.00000000e+00,
        -2.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -2.00000000e+00,
        -1.00000000e+00]])

In [23]:
q @ h

array([[ 6.84462111e+00,  5.70789502e-10,  2.04782022e-08,
        -1.09837474e-07],
       [-9.95942856e-08,  6.89347377e-01,  2.36081499e-01,
         2.14828864e+00],
       [-5.06451524e-08,  1.49659118e+00,  1.47676246e+00,
        -6.39237600e-01],
       [ 8.17356173e-12,  7.22909643e-01, -7.95200607e-01,
        -1.44581929e-01]])