In [1]:
import scipy as scipy
from numpy import loadtxt
import numpy as np

from src.linear_algebra_resolution.gaussian_elimination import gaussian_elimination
from src.linear_algebra_resolution.qr_decomposition import qr_decomposition, qr_method

In [2]:
x = loadtxt('test_matrix/householder_not_simetric.csv', delimiter=',')

In [3]:
x

array([[66., 78., 47., 85., 20., 61., 36., 13.],
       [54., 33., 44., 36., 82., 68., 93., 47.],
       [25., 68., 69.,  2., 11., 13., 74., 82.],
       [70., 67., 43., 31., 20., 54., 96., 73.],
       [ 5., 50., 16., 33.,  9.,  8., 54.,  6.],
       [ 3., 69., 46.,  6., 12.,  6., 53., 57.],
       [97., 16.,  1., 17., 77.,  2., 42., 18.],
       [52.,  7., 57., 86.,  1., 43., 98., 79.]])

In [4]:
x.T

array([[66., 54., 25., 70.,  5.,  3., 97., 52.],
       [78., 33., 68., 67., 50., 69., 16.,  7.],
       [47., 44., 69., 43., 16., 46.,  1., 57.],
       [85., 36.,  2., 31., 33.,  6., 17., 86.],
       [20., 82., 11., 20.,  9., 12., 77.,  1.],
       [61., 68., 13., 54.,  8.,  6.,  2., 43.],
       [36., 93., 74., 96., 54., 53., 42., 98.],
       [13., 47., 82., 73.,  6., 57., 18., 79.]])

In [5]:
x.shape

(8, 8)

In [6]:
eignvalues, eigvectors = qr_method(x)

In [13]:
np.vstack(eigvectors)

array([[ 9.97903228e-01+0.00000000e+00j,  3.62920633e-02+0.00000000e+00j,
        -1.55782658e-03+0.00000000e+00j, -4.44311404e-02+0.00000000e+00j,
        -1.83397060e-02+0.00000000e+00j,  2.19624734e-02+0.00000000e+00j,
         4.45378801e-03+0.00000000e+00j, -7.54651721e-03+0.00000000e+00j],
       [ 9.93287187e-01+0.00000000e+00j,  7.45656735e-02+0.00000000e+00j,
        -3.23633240e-02+0.00000000e+00j, -4.13547023e-02+0.00000000e+00j,
        -4.04532898e-02+0.00000000e+00j,  3.69985614e-02+0.00000000e+00j,
         4.23300208e-02+0.00000000e+00j, -1.63014046e-02+0.00000000e+00j],
       [ 9.98244238e-01-1.96127525e-02j,  2.13199266e-02-8.11797543e-04j,
         1.20463899e-02+1.26931203e-04j, -4.56405482e-02+8.62250375e-04j,
        -8.50651120e-03+4.28596680e-04j,  1.45669112e-02-4.88684600e-04j,
        -1.17602287e-02-1.97462328e-04j, -4.03720601e-03+1.69283767e-04j],
       [ 9.98244238e-01+1.96127525e-02j,  2.13199266e-02+8.11797543e-04j,
         1.20463899e-02-1.26931203e

In [8]:
eignvalues

array([ -69.67435269+0.j, -352.01379449+0.j,  -23.42865101+1.j,
        -23.42865101-1.j,  -57.80470656+0.j,   45.17252787+1.j,
         45.17252787-1.j,   14.60431309+0.j])

In [9]:
true_eigvalues, true_eigvectors = np.linalg.eig(x)

In [10]:
true_eigvalues

array([352.01379432 +0.j        ,  23.42865115+61.56092331j,
        23.42865115-61.56092331j, -45.17252787+20.80048361j,
       -45.17252787-20.80048361j, -57.80470654 +0.j        ,
        14.60431309 +0.j        ,  69.67435255 +0.j        ])

In [14]:
np.vstack(eigvectors)

array([[ 9.97903228e-01+0.00000000e+00j,  3.62920633e-02+0.00000000e+00j,
        -1.55782658e-03+0.00000000e+00j, -4.44311404e-02+0.00000000e+00j,
        -1.83397060e-02+0.00000000e+00j,  2.19624734e-02+0.00000000e+00j,
         4.45378801e-03+0.00000000e+00j, -7.54651721e-03+0.00000000e+00j],
       [ 9.93287187e-01+0.00000000e+00j,  7.45656735e-02+0.00000000e+00j,
        -3.23633240e-02+0.00000000e+00j, -4.13547023e-02+0.00000000e+00j,
        -4.04532898e-02+0.00000000e+00j,  3.69985614e-02+0.00000000e+00j,
         4.23300208e-02+0.00000000e+00j, -1.63014046e-02+0.00000000e+00j],
       [ 9.98244238e-01-1.96127525e-02j,  2.13199266e-02-8.11797543e-04j,
         1.20463899e-02+1.26931203e-04j, -4.56405482e-02+8.62250375e-04j,
        -8.50651120e-03+4.28596680e-04j,  1.45669112e-02-4.88684600e-04j,
        -1.17602287e-02-1.97462328e-04j, -4.03720601e-03+1.69283767e-04j],
       [ 9.98244238e-01+1.96127525e-02j,  2.13199266e-02+8.11797543e-04j,
         1.20463899e-02-1.26931203e

In [11]:
true_eigvectors

array([[ 0.41703759+0.j        ,  0.55509994+0.j        ,
         0.55509994-0.j        , -0.09603021+0.20490786j,
        -0.09603021-0.20490786j, -0.16771061+0.j        ,
         0.23760349+0.j        ,  0.05825632+0.j        ],
       [ 0.40392465+0.j        , -0.04944571+0.19187464j,
        -0.04944571-0.19187464j, -0.11851959+0.15291271j,
        -0.11851959-0.15291271j, -0.47128673+0.j        ,
        -0.11513513+0.j        , -0.26363876+0.j        ],
       [ 0.34550884+0.j        , -0.08085905+0.33225594j,
        -0.08085905-0.33225594j,  0.12277761-0.17624308j,
         0.12277761+0.17624308j,  0.37953693+0.j        ,
         0.72555785+0.j        ,  0.37425647+0.j        ],
       [ 0.44742963+0.j        , -0.02881343-0.01861535j,
        -0.02881343+0.01861535j, -0.05874166-0.26862163j,
        -0.05874166+0.26862163j,  0.11035514+0.j        ,
        -0.3038945 +0.j        ,  0.12919714+0.j        ],
       [ 0.17655718+0.j        , -0.19058885+0.05103895j,
        -0

In [12]:
diag_roots = np.diag(merged)

NameError: name 'merged' is not defined

In [ ]:
matrix_to_solve = r - diag_roots

In [ ]:
m = np.column_stack(
    [matrix_to_solve,
     np.zeros(matrix_to_solve.shape[0])
     ])

In [ ]:
x_complex = scipy.sparse.linalg.spsolve(matrix_to_solve,dtype=np.cfloat)

In [ ]:
x_complex

In [ ]:
gaussian_elimination(matrix_to_solve, np.zeros(matrix_to_solve.shape[0]))

In [ ]:
q, r = qr_decomposition(x)

In [ ]:
# q @ r