In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.svd_decomposition import svd

In [2]:
x = loadtxt('test_matrix/householder_simetric.csv', delimiter=',')

In [3]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [4]:
sample_svd = np.array([
    [1,2,3],
    [4,5,6]
  ])

In [12]:
singular_values, us, vs = svd(x)

In [13]:
us @ singular_values @ vs

array([[ 4.00000000e+00,  1.00000000e+00, -2.00000000e+00,
         2.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00, -2.29690019e-17,
         1.00000000e+00],
       [-2.00000000e+00, -1.54299864e-16,  3.00000000e+00,
        -2.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -2.00000000e+00,
        -1.00000000e+00]])

In [14]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])