In [6]:
from src.linear_algebra_resolution.sor import sor_solver
from numpy import loadtxt
import numpy as np

In [3]:
x_b = loadtxt('test_matrix/sor_b.csv', delimiter=',')

x = x_b[:,:-1]
b = x_b[:,-1]

In [4]:
x

array([[2., 1.],
       [5., 7.]])

In [5]:
b

array([11., 13.])

In [7]:
sor_solver(x, b, 1.5)

array([ 7.11111111, -3.22222222])