In [7]:
from src.linear_algebra_resolution.grad_conj import conjugate_gradient
from src.linear_algebra_resolution.sor import sor_solver
from numpy import loadtxt
import numpy as np
from scipy.sparse.linalg import cg

In [3]:
x_b = loadtxt('test_matrix/conjugate_gradient_b.csv', delimiter=',')

x = x_b[:,:-1]
b = x_b[:,-1]

In [4]:
x

array([[ 2.5409, -0.0113],
       [-0.0113,  0.5287]])

In [5]:
b

array([1.3864, 0.3719])

In [6]:
conjugate_gradient(x, b)

array([0.5488139 , 0.71515339])

In [8]:
cg(x, b)

(array([0.5488139 , 0.71515339]), 0)