In [1]:
import numpy as np
from numpy import loadtxt
from src.linear_algebra_resolution.gauss_jordam_elimination import gaussian_jordam_elimination

In [2]:
gauss_partial_pivoting_b_path = 'test_matrix/gauss_partial_pivoting_b.csv'
gauss_partial_pivoting_b = loadtxt(gauss_partial_pivoting_b_path, delimiter=',')

gauss_partial_pivoting = gauss_partial_pivoting_b[:,:-1]
b = gauss_partial_pivoting_b[:,-1]

In [3]:
gauss_partial_pivoting

array([[5., 1., 0., 2., 1.],
       [0., 4., 0., 1., 2.],
       [1., 1., 4., 1., 1.],
       [0., 1., 2., 6., 0.],
       [0., 0., 1., 2., 4.]])

In [4]:
resp, hist = gaussian_jordam_elimination(gauss_partial_pivoting, b)

In [5]:
gauss_partial_pivoting @ resp

array([1., 2., 3., 4., 5.])

In [6]:
b

array([1., 2., 3., 4., 5.])

In [8]:
m = hist.apply_operations_matrix()

In [9]:
gauss_partial_pivoting @ m

array([[ 5.00000000e+00,  1.00000000e+00, -6.24500451e-17,
         2.00000000e+00,  1.00000000e+00],
       [-6.93889390e-18,  4.00000000e+00, -7.28583860e-17,
         1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  4.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         6.00000000e+00, -5.55111512e-17],
       [-1.38777878e-17, -9.19403442e-17,  1.00000000e+00,
         2.00000000e+00,  4.00000000e+00]])

In [10]:
gauss_partial_pivoting

array([[5., 1., 0., 2., 1.],
       [0., 4., 0., 1., 2.],
       [1., 1., 4., 1., 1.],
       [0., 1., 2., 6., 0.],
       [0., 0., 1., 2., 4.]])

In [13]:
inv = hist.get_acum_op_matrix()

In [15]:
np.isclose(gauss_partial_pivoting @ inv, np.eye(5))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [16]:
gauss_partial_pivoting @ inv

array([[ 1.00000000e+00, -2.08166817e-17,  3.46944695e-18,
        -8.32667268e-17,  0.00000000e+00],
       [ 1.73472348e-18,  1.00000000e+00, -6.93889390e-18,
         0.00000000e+00,  0.00000000e+00],
       [-9.54097912e-18, -2.08166817e-17,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.38777878e-17,  0.00000000e+00, -2.77555756e-17,
         1.00000000e+00,  6.93889390e-18],
       [ 3.46944695e-18, -2.77555756e-17, -1.38777878e-17,
         0.00000000e+00,  1.00000000e+00]])