In [71]:
from src.linear_algebra_resolution.lu_decomposition import lu_resolution
from numpy import loadtxt

In [72]:
path = 'test_matrix/gauss_partial_pivoting_b.csv'
x_b = loadtxt(path, delimiter=',')

x = x_b[:,:-1]
b = x_b[:,-1]

In [73]:
x

array([[5., 1., 0., 2., 1.],
       [0., 4., 0., 1., 2.],
       [1., 1., 4., 1., 1.],
       [0., 1., 2., 6., 0.],
       [0., 0., 1., 2., 4.]])

In [74]:
l, u, resp = lu_resolution(x, b)

In [75]:
# Vetor Resposta
resp

array([-0.17083787, -0.06746464,  0.46028292,  0.52448313,  0.8726877 ])

In [76]:
# Matriz @ Vetor de Resposta
x @ resp

array([1., 2., 3., 4., 5.])

In [77]:
# Lower Matrix
l

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.2       , 0.2       , 1.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.5       , 1.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.34234234, 1.        ]])

In [78]:
# Upper Matrix
u

array([[ 5.        ,  1.        ,  0.        ,  2.        ,  1.        ],
       [ 0.        ,  4.        ,  0.        ,  1.        ,  2.        ],
       [ 0.        ,  0.        ,  4.        ,  0.4       ,  0.4       ],
       [ 0.        ,  0.        ,  0.        ,  5.55      , -0.7       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  4.13963964]])

In [79]:
# Lower @ Upper
l @ u

array([[5., 1., 0., 2., 1.],
       [0., 4., 0., 1., 2.],
       [1., 1., 4., 1., 1.],
       [0., 1., 2., 6., 0.],
       [0., 0., 1., 2., 4.]])