In [1]:
import numpy as np
from numpy import loadtxt
from src.linear_algebra_resolution import History

In [16]:
gauss_partial_pivoting_b_path = 'test_matrix/lu_example.csv'
gauss_partial_pivoting_b = loadtxt(gauss_partial_pivoting_b_path, delimiter=',')

gauss_partial_pivoting = gauss_partial_pivoting_b[:,:-1]
b = gauss_partial_pivoting_b[:,-1]

In [17]:
gauss_partial_pivoting

array([[ 1.,  1., -1.],
       [ 1., -2.,  3.],
       [ 2.,  3.,  1.]])

In [63]:
def lu_decomposition(x: np.ndarray) -> tuple[np.ndarray, np.ndarray]:

	x = x.copy()

	n = x.shape[0]
	u = np.eye(n)
	l = np.eye(n)

	for k in range(n):

		if np.isclose(x[k,k], 0):
			print('0 no pivot')
			break

		u[k,k] = x[k,k]

		for i in range(k+1, n):
			l[i, k] = x[i, k] / u[k, k]
			print(l[i, k])

			u[k,i] = x[k,i]

		for i in range(k+1, n):
			for j in range(k+1, n):
				x[i, j] = x[i, j] - l[i, k] * u[k, j]

	return l, u

In [64]:
A = np.array([[7, 3, -1], [3, 8, 1], [-1, 1, 4]])

In [65]:
l, u = lu_decomposition(A)

0.42857142857142855
-0.14285714285714285
0.16666666666666666


In [66]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ],
       [-0.14285714,  0.16666667,  1.        ]])

In [67]:
u

array([[ 7.,  3., -1.],
       [ 0.,  6.,  1.],
       [ 0.,  0.,  2.]])