In [1]:
from src.linear_algebra_resolution.cholesky_decomposition import cholesky_decomposition
from numpy import loadtxt

In [2]:
path = 'test_matrix/cholesky.csv'
x_b = loadtxt(path, delimiter=',')

x = x_b


In [3]:
x

array([[ 7.3,  1. ,  0. ],
       [ 1. , 20. ,  3.5],
       [ 0. ,  3.5,  2. ]])

In [10]:
g = cholesky_decomposition(x)

In [11]:
g

array([[2.70185122, 0.        , 0.        ],
       [0.37011661, 4.45679411, 0.        ],
       [0.        , 0.78531786, 1.17612749]])

In [12]:
x

array([[ 7.3,  1. ,  0. ],
       [ 1. , 20. ,  3.5],
       [ 0. ,  3.5,  2. ]])

In [13]:
g @ g.T

array([[ 7.3,  1. ,  0. ],
       [ 1. , 20. ,  3.5],
       [ 0. ,  3.5,  2. ]])