In [7]:
from src.linear_algebra_resolution.gram_schmidt import gram_schmidt_from_cholesky
from numpy import loadtxt
import numpy as np

In [2]:
path = 'test_matrix/cholesky_2.csv'
x_b = loadtxt(path, delimiter=',')

x = x_b

In [3]:
x

array([[ 16., -12., -12., -16.],
       [-12.,  25.,   1.,  -4.],
       [-12.,   1.,  17.,  14.],
       [-16.,  -4.,  14.,  57.]])

In [4]:
g, gm = gram_schmidt_from_cholesky(x)

In [5]:
g

array([[ 4.,  0.,  0.,  0.],
       [-3.,  4.,  0.,  0.],
       [-3., -2.,  2.,  0.],
       [-4., -4., -3.,  4.]])

In [6]:
gm.T

array([[ 0.56568542, -0.42426407, -0.42426407, -0.56568542],
       [-0.13719887,  0.78889349, -0.24009802, -0.54879547],
       [-0.09683641, -0.16946371,  0.79890034, -0.56891388],
       [ 0.80734081,  0.41100987,  0.35229417,  0.23486278]])

In [9]:
inv = np.linalg.inv(gm)
inv

array([[ 0.56568542, -0.42426407, -0.42426407, -0.56568542],
       [-0.13719887,  0.78889349, -0.24009802, -0.54879547],
       [-0.09683641, -0.16946371,  0.79890034, -0.56891388],
       [ 0.80734081,  0.41100987,  0.35229417,  0.23486278]])