In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.power_methods import inverse_power_method, regular_power_method, shifted_power_method


In [2]:
path = 'test_matrix/power_method.csv'
x = loadtxt(path, delimiter=',')

In [3]:
x

array([[0., 2.],
       [2., 3.]])

In [4]:
regular_power_method(x)

(array([0.44692242, 0.89457272]), 3.999991522909338, True)

In [5]:
inverse_power_method(x)

(array([-0.89434529,  0.44737736]), -1.0000006705523437, True)

In [12]:
shifted_power_method(x, mu=2)

(array([0.44376347, 0.89614395]), 4.000111383466319, True)