In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.householder_method import householder
from src.linear_algebra_resolution.power_methods import regular_power_method


In [3]:
x = loadtxt('test_matrix/householder_simetric.csv', delimiter=',')

In [4]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [5]:
a_hat, h = householder(x)

In [8]:
np.around(a_hat, 5)

array([[ 4.     ,  3.     , -0.     , -0.     ],
       [ 3.     ,  3.33333,  1.66667, -0.     ],
       [-0.     ,  1.66667, -1.32   , -0.90667],
       [-0.     ,  0.     , -0.90667,  1.98667]])

In [7]:
h

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.13333333,  0.93333333],
       [ 0.        , -0.66666667, -0.66666667,  0.33333333],
       [ 0.        ,  0.66666667, -0.73333333, -0.13333333]])