In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.householder_method import householder
from src.linear_algebra_resolution.power_methods import regular_power_method


In [7]:
x = loadtxt('test_matrix/householder_c.csv', delimiter=',')

In [8]:
x

array([[38.,  4.,  0.,  0.,  1.],
       [ 4., 11.,  1.,  4.,  4.],
       [ 0.,  1., 51.,  0.,  1.],
       [ 0.,  4.,  0., 36.,  2.],
       [ 1.,  4.,  1.,  2., 60.]])

In [9]:
a_hat, h = householder(x)

In [10]:
a_hat

array([[ 3.80000000e+01,  4.12310563e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 4.12310563e+00,  1.57647059e+01,  1.57256980e+01,
        -4.31382575e-16,  3.73875282e-17],
       [ 0.00000000e+00,  1.57256980e+01,  5.43509387e+01,
         4.34939853e+00, -5.50337343e-16],
       [ 0.00000000e+00,  5.26173487e-16,  4.34939853e+00,
         3.70884007e+01, -1.27305513e+00],
       [ 0.00000000e+00,  3.99165315e-16,  9.96733266e-17,
        -1.27305513e+00,  5.07959547e+01]])

In [11]:
h

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9701425 , -0.2322505 , -0.06537016, -0.02469774],
       [ 0.        ,  0.        ,  0.07711442,  0.10078308, -0.99191539],
       [ 0.        ,  0.        ,  0.27761192, -0.95770423, -0.07572471],
       [ 0.        ,  0.24253563,  0.92900199,  0.26148064,  0.09879096]])