In [1]:
from numpy import loadtxt
import numpy as np
from src.linear_algebra_resolution.householder_method import householder
from src.linear_algebra_resolution.power_methods import regular_power_method


In [12]:
x = loadtxt('test_matrix/householder.csv', delimiter=',')

In [13]:
x

array([[ 4.,  1., -2.,  2.],
       [ 1.,  2.,  0.,  1.],
       [-2.,  0.,  3., -2.],
       [ 2.,  1., -2., -1.]])

In [14]:
a_hat, h = householder(x)

In [15]:
a_hat

array([[ 4.00000000e+00,  3.00000000e+00, -1.99840144e-16,
        -8.43769499e-16],
       [ 3.00000000e+00,  3.33333333e+00,  1.66666667e+00,
        -2.88657986e-16],
       [-1.99840144e-16,  1.66666667e+00, -1.32000000e+00,
        -9.06666667e-01],
       [-8.43769499e-16,  2.22044605e-16, -9.06666667e-01,
         1.98666667e+00]])

In [16]:
h

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.13333333,  0.93333333],
       [ 0.        , -0.66666667, -0.66666667,  0.33333333],
       [ 0.        ,  0.66666667, -0.73333333, -0.13333333]])